variables:
  IMAGE_NAME: "${CI_REGISTRY_IMAGE}"

stages:
  - build
  - test

image: registry.gitlab.com/jakubigla/docker-compose-image

services:
  - docker:dind

before_script:
  - docker --version
  - docker-compose --version
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

api:
  stage: build
  script:
    - docker-compose build api
    - docker-compose push api
  tags:
    - docker

integration:
  variables:
    COMPOSE_FILE: docker-compose.yml:docker-compose.dev.yml
    POSTMAN_SLEEP: 15
  stage: test
  script:
    - docker-compose run --rm postman
  tags:
    - docker