variables:
  IMAGE_NAME: "${CI_REGISTRY_IMAGE}"
  NEWMAN_IMAGE_NAME: "${CI_REGISTRY_IMAGE}/newman"

stages:
  - build
  - test

image: registry.gitlab.com/jakubigla/docker-compose-image

services:
  - docker:dind

before_script:
  - docker --version
  - docker-compose --version
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

api:
  stage: build
  script:
    - docker-compose build api postman
    - docker-compose push api postman
  tags:
    - docker

integration:
  variables:
    POSTMAN_SLEEP: 20
  stage: test
  script:
    - docker-compose pull
    - docker-compose run --rm postman
  tags:
    - docker