version: "2.1"

services:
  api:
    image: "${IMAGE_NAME:-demo-api}"
    ports:
      - 80:8080
    build:
      context: .
    environment:
      SONAR_ENABLED: "${SONAR_ENABLED:-false}"
      SONAR_URL: "${SONAR_URL:-http://host.docker.internal:9000}"
      SONAR_ORGANIZATION: "${SONAR_ORGANIZATION:-default-organization}"
      SONAR_USERNAME: "${SONAR_USERNAME:-admin}"
      SONAR_PASSWORD: "${SONAR_PASSWORD-admin}"
      SONAR_BRANCH: "${SONAR_BRANCH:-}"
    depends_on:
      - db

  db:
    image: mysql:5
    environment:
      MYSQL_USER: demouser
      MYSQL_PASSWORD: companyday
      MYSQL_DATABASE: notes_app
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"

  postman:
    image: postman/newman
    entrypoint: []
    command: sh -c "sleep ${POSTMAN_SLEEP:-0} && newman run --global-var \"url=http://api:8080\" ${CI_PROJECT_DIR:-.}/postman/valtech-demo.postman_collection.json"
    depends_on:
      - api