version: "2.1"

services:
  api:
    image: "${IMAGE_NAME:-demo-api}"
    ports:
      - 80:8080
    build:
      context: .
    depends_on:
      - db

  db:
    image: mysql:5
    environment:
      MYSQL_USER: demouser
      MYSQL_PASSWORD: companyday
      MYSQL_DATABASE: notes_app
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"