version: "2.1"

services:
  sonar:
    image: sonarqube:latest

  postman:
    image: postman/newman
    entrypoint: []
    command: sh -c "sleep ${POSTMAN_SLEEP:-0} && newman run --global-var \"url=http://api:8080\" valtech-demo.postman_collection.json"
    depends_on:
      - api
