version: "2.1"

services:

  api:
    image: "${IMAGE_NAME:-valtech/demo-api}"
    depends_on:
      - liquibase

  db:
    image: mysql:5
    environment:
      MYSQL_USER: demouser
      MYSQL_PASSWORD: companyday
      MYSQL_DATABASE: notes_app
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
         
  liquibase:
    image: "${LIQUIBASE_IMAGE_NAME:-valtech/demo-api/liquibase}"
    environment:
      LIQUIBASE_HOST: db
      LIQUIBASE_DATABASE: notes_app
      LIQUIBASE_USERNAME: demouser
      LIQUIBASE_PASSWORD: companyday
      LIQUIBASE_CHANGELOG: database-changelog.sql
    command: sh -c "liquibase update"
    depends_on:
      - db

  postman:
    image: "${NEWMAN_IMAGE_NAME:-valtech/demo-api/newman}"
    entrypoint: []
    command: sh -c "newman run --global-var \"url=http://api:8080\" valtech-demo.postman_collection.json"
    depends_on:
      - api